version: '3'
services:
  redis:
    image: redis
    restart: always
    ports:
      - "16379:6379"
  postgresql:
    image: postgres
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: example